
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: db
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}