apiVersion: apps/v1
kind: StatefulSet 
metadata:
  labels:
    app: db
  name: db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: postgres
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        type: {{ .Values.nodeSelector.type }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: {{ .Values.secrets.database }}
        volumeMounts:
        - name: pgdata 
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: {{ toYaml .Values.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
