name: vagrant-deployment

services:
    api1:
      networks:
          - app_network
      container_name: api1
      env_file:
          - students_fastapi/.env
      ports:
          - 8081:8000
      build: .
      image: students_fastapi:1.0.0

    api2:
      networks:
          - app_network
      container_name: api2
      env_file:
          - students_fastapi/.env
      ports:
          - 8082:8000
      build: .
      image: students_fastapi:1.0.0

    nginx:
      image: nginx:latest
      container_name: nginx
      depends_on:
        - api1
        - api2
      ports:
        - 8080:80
      networks:
          - app_network      
      volumes:
          - ./nginx/sites-enabled/default:/etc/nginx/sites-enabled/default:ro


networks:
  app_network:
    external: true
    name: myapp-net