apiVersion: v1
kind: Namespace
metadata:
  name: student-api
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector: 
        type: application
      restartPolicy: Always
      containers:
      - image: pmgoriya/one2n-sre-bootcamp:1.0.0
        name: one2n-sre-bootcamp
        resources: {}
        envFrom:
          - secretRef:
              name: database-credentials
          - configMapRef:
              name: database-config
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      initContainers:
      - name: db-migrations
        image: pmgoriya/one2n-sre-bootcamp:builder
        envFrom:
          - secretRef:
              name: database-credentials
          - configMapRef:
              name: database-config
        env:
          - name: PATH
            value: "/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          - name: PYTHONPATH
            value: "/install/lib/python3.12/site-packages"
        command: ["alembic", "upgrade", "head"]
status: {}
---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: student-api
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}
