apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: student-api
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: secret
      version: v1
      auth:
        tokenSecretRef:
          name: vault-token
          key: token