apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: database/creds
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: database/creds
        property: DB_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: database/creds
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: database/creds
        property: POSTGRES_USER
