apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      version: {{ .Values.vault.version }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecretRef.name }}
          key: {{ .Values.vault.tokenSecretRef.key }}
