apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api 
  name: api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector: 
        type: {{ .Values.nodeSelector.type }}
      restartPolicy: Always
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: one2n-sre-bootcamp
        resources: {}
        envFrom:
          - secretRef:
              name: {{ .Values.envFrom.secretRef }}
          - configMapRef:
              name: {{ .Values.envFrom.configMapRef }}
      initContainers:
      - name: db-migrations
        image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
        envFrom:
          - secretRef:
              name: {{ .Values.envFrom.secretRef }}
          - configMapRef:
              name: {{ .Values.envFrom.secretRef }}
        env:
          - name: PATH
            value: "/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          - name: PYTHONPATH
            value: "/install/lib/python3.12/site-packages"
        command: ["alembic", "upgrade", "head"]
status: {}