---

name: Project CI

on:
    push:
        branches: [master]
        paths:
            - 'students_fastapi/**'
    workflow_dispatch:

jobs:
    test:
        runs-on: self-hosted

        env:
            VERSION: 1.0.0
            IMAGE_NAME: pmgoriya/one2n-sre-bootcamp
            FULL_IMAGE: pmgoriya/one2n-sre-bootcamp:${{ env.VERSION }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Run Linter
              run: make lint

            - name: Lint Dockerfile
              run: hadolint Dockerfile

            - name: Run build
              run: docker build -t $FULL_IMAGE .

            - name: Docker login 
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Docker push
              run: docker push $FULL_IMAGE